# Site Information
title: Zhang
description: "从事 LLM 推理部署、视觉算法开发、模型压缩部署以及算法SDK开发工作,终身学习践行者。"
url: https://www.armcvai.cn
repo: harleyszhang/harleyszhang.github.io
lang: zh-CN
timezone: Africa/El_Aaiun

# Social Media and External URLs
github: harleyszhang
zhihu: tang-fen-44-49
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "About"
    url: "/about.html"
  - title: "Weekly"
    url: "https://zhg-weekly.vercel.app/"

# SEO and Analytics
google_analytics: G-PL13W62QF9

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: false
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: true
payImage: //gw.alipayobjects.com/zos/k/vb/1.png
assetUrl: //tw93.fun/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==